theme: jekyll-theme-minimal
title: strange attractions, the homepage
description: "The beginnings of a homepage, stay tuned. This should eventually contain" | "- Some programming, split between bioinformatics and type theory, and possibly some overlaps between them (type-directed bioinformatics pipelines...imagine...)" | "- Some mathematical modeling of biological systems" | "- Some mathematics proper" | "- Writing"
